In [2]:
import torch
import numpy as np
import time

device = 'CUDA' if torch.cuda.is_available() else 'CPU'
print(device)

CPU


[LLM_LeaderBoard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)

## Methods of using torch

In [19]:
randint = torch.randint(-100, 100,(5,))
#print(randint)
tensor = torch.tensor([[1, 2], [5, 6], [7, 9], [0, 2]])
#print(tensor)
zeros = torch.zeros(3, 4)
#print(tensor)
ones = torch.ones(3, 4)
#print(ones)
input = torch.empty(3, 4)
#print(input)
arrange = torch.arange(5)
#print(arrange)
linspace = torch.linspace(3, 10, steps=5)
logspace = torch.logspace(start = -10, end = 10 , steps=5)
linspace #logspace 

eye = torch.eye(5)
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like


tensor([ 11,  12,  23,  98, -14])
tensor([[1, 2],
        [5, 6],
        [7, 9],
        [0, 2]])
tensor([[1, 2],
        [5, 6],
        [7, 9],
        [0, 2]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([0, 1, 2, 3, 4])


tensor([[0, 0, 0],
        [0, 0, 0]])

# Calculate the performance 
#### Which we can see GPU is faster than CPU when the data is big

In [6]:
start_time = time.time()
zeros = torch.zeros(2,2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0003900528


# Opening txt

In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print("\n")
print(len(chars))

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '•', '™']


91


# Tokenizer

In [8]:
# {'a':0, 'b':1....}
string_to_int = {ch: i for i, ch in enumerate(chars)}
# {'1': a, '2': b....}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

#kk = encode('hellosdfoijtw;a')
#decode(kk)

# array, which support GPU Acceralation
data = torch.tensor(encode(text), dtype = torch.long)
print(data[:100])

tensor([48, 65, 62,  1, 44, 75, 72, 67, 62, 60, 77,  1, 35, 78, 77, 62, 71, 59,
        62, 75, 64,  1, 62, 30, 72, 72, 68,  1, 72, 63,  1, 32, 72, 75, 72, 77,
        65, 82,  1, 58, 71, 61,  1, 77, 65, 62,  1, 51, 66, 83, 58, 75, 61,  1,
        66, 71,  1, 43, 83,  0,  1,  1,  1,  1,  0, 48, 65, 66, 76,  1, 62, 59,
        72, 72, 68,  1, 66, 76,  1, 63, 72, 75,  1, 77, 65, 62,  1, 78, 76, 62,
         1, 72, 63,  1, 58, 71, 82, 72, 71, 62])


# Text Corpus (語料庫)
#### Spilt data by 80%, 20% to make sure the data are unique ?
#### What is Bigram Model 

In [9]:
n = int(0.8*len(data))
train_data = data[:n]
valid_data = data[:n]

In [14]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print('When input is', context, ',target is: ', target)

When input is tensor([48]) ,target is:  tensor(65)
When input is tensor([48, 65]) ,target is:  tensor(62)
When input is tensor([48, 65, 62]) ,target is:  tensor(1)
When input is tensor([48, 65, 62,  1]) ,target is:  tensor(44)
When input is tensor([48, 65, 62,  1, 44]) ,target is:  tensor(75)
When input is tensor([48, 65, 62,  1, 44, 75]) ,target is:  tensor(72)
When input is tensor([48, 65, 62,  1, 44, 75, 72]) ,target is:  tensor(67)
When input is tensor([48, 65, 62,  1, 44, 75, 72, 67]) ,target is:  tensor(62)


# Torch Functions

In [8]:
# randomly generate stuff between 0.1 => 0, and 0.9 => 1
p = torch.tensor([0.1, 0.9])
sample = torch.multinomial(p, num_samples=3, replacement=True)
print(sample)

tensor([0, 1, 0])


In [15]:
# concatenate
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([9])), dim=0)
out

tensor([1, 2, 3, 4, 9])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
# exponential 
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
# initialize a matrix with zeros
input = torch.zeros(2, 3, 4)
print(input.shape)
# swap the element 0 and 2
out = input.transpose(0, 2)
print(out.shape)

torch.Size([2, 3, 4])


torch.Size([4, 3, 2])

In [24]:
# stack tensor together
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
print(stacked_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# Torch NN(Trainer)

#### [Torch_NN Document](https://pytorch.org/docs/stable/nn.html)

In [3]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))

tensor([6.4539, 3.0986, 6.7468], grad_fn=<SqueezeBackward4>)


#### Softmax function: probability distribution

In [3]:
import torch.nn.functional as f
tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output = f.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [8]:
# initialize embedding layer
vocab_size = 1000
embedded_dim = 100
embedding = nn.Embedding(vocab_size, embedded_dim)

input_indices = torch.LongTensor([1, 3, 5, 4])

embedded_output = embedding(input_indices)
print(embedded_output.shape)

torch.Size([4, 100])


### Multiply two tensor(matrix)

In [4]:
a = torch.tensor([[2, 3], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)
# printf(torch.matmul(a, b))

tensor([[ 44,  49,  54],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Type Transformation

In [5]:
int_64 = torch.randint(1, (3, 2)).float()
float_64 = torch.rand(2, 3)
result = torch.matmul(int_64, float_64)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [1]:
#!pip install pennylane

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.4/165.4 kB 731.1 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 662.9 kB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 158.6 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 kB 138.8 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 92.6 kB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 247.9 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 123.7 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 151.2 kB/s eta 0:00:0000:0100:06
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492024 sha256=88327b52cb6dfc68eea714f7b1af0ce0da0d8c14939736ed986df32ac2a0d002
  Stored in directory: /Users/harry/Library/Caches/pip/wheels/da/19/ca/9d8c44cd311a955509d7e1