In [2]:
import torch
import numpy as np
import time

device = 'CUDA' if torch.cuda.is_available() else 'CPU'
print(device)

CPU


[LLM_LeaderBoard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)

## Methods of using torch

In [19]:
randint = torch.randint(-100, 100,(5,))
#print(randint)
tensor = torch.tensor([[1, 2], [5, 6], [7, 9], [0, 2]])
#print(tensor)
zeros = torch.zeros(3, 4)
#print(tensor)
ones = torch.ones(3, 4)
#print(ones)
input = torch.empty(3, 4)
#print(input)
arrange = torch.arange(5)
#print(arrange)
linspace = torch.linspace(3, 10, steps=5)
logspace = torch.logspace(start = -10, end = 10 , steps=5)
linspace #logspace 

eye = torch.eye(5)
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like


tensor([ 11,  12,  23,  98, -14])
tensor([[1, 2],
        [5, 6],
        [7, 9],
        [0, 2]])
tensor([[1, 2],
        [5, 6],
        [7, 9],
        [0, 2]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([0, 1, 2, 3, 4])


tensor([[0, 0, 0],
        [0, 0, 0]])

# Calculate the performance 
#### Which we can see GPU is faster than CPU when the data is big

In [6]:
start_time = time.time()
zeros = torch.zeros(2,2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0003900528


# Opening txt

In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print("\n")
print(len(chars))

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '•', '™']


91


# Tokenizer

In [8]:
# {'a':0, 'b':1....}
string_to_int = {ch: i for i, ch in enumerate(chars)}
# {'1': a, '2': b....}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

#kk = encode('hellosdfoijtw;a')
#decode(kk)

# array, which support GPU Acceralation
data = torch.tensor(encode(text), dtype = torch.long)
print(data[:100])

tensor([48, 65, 62,  1, 44, 75, 72, 67, 62, 60, 77,  1, 35, 78, 77, 62, 71, 59,
        62, 75, 64,  1, 62, 30, 72, 72, 68,  1, 72, 63,  1, 32, 72, 75, 72, 77,
        65, 82,  1, 58, 71, 61,  1, 77, 65, 62,  1, 51, 66, 83, 58, 75, 61,  1,
        66, 71,  1, 43, 83,  0,  1,  1,  1,  1,  0, 48, 65, 66, 76,  1, 62, 59,
        72, 72, 68,  1, 66, 76,  1, 63, 72, 75,  1, 77, 65, 62,  1, 78, 76, 62,
         1, 72, 63,  1, 58, 71, 82, 72, 71, 62])


# Text Corpus (語料庫)
#### Spilt data by 80%, 20% to make sure the data are unique ?
#### What is Bigram Model 

In [9]:
n = int(0.8*len(data))
train_data = data[:n]
valid_data = data[:n]

In [14]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print('When input is', context, ',target is: ', target)

When input is tensor([48]) ,target is:  tensor(65)
When input is tensor([48, 65]) ,target is:  tensor(62)
When input is tensor([48, 65, 62]) ,target is:  tensor(1)
When input is tensor([48, 65, 62,  1]) ,target is:  tensor(44)
When input is tensor([48, 65, 62,  1, 44]) ,target is:  tensor(75)
When input is tensor([48, 65, 62,  1, 44, 75]) ,target is:  tensor(72)
When input is tensor([48, 65, 62,  1, 44, 75, 72]) ,target is:  tensor(67)
When input is tensor([48, 65, 62,  1, 44, 75, 72, 67]) ,target is:  tensor(62)


# Torch Functions

In [8]:
# randomly generate stuff between 0.1 => 0, and 0.9 => 1
p = torch.tensor([0.1, 0.9])
sample = torch.multinomial(p, num_samples=3, replacement=True)
print(sample)

tensor([0, 1, 0])


In [15]:
# concatenate
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([9])), dim=0)
out

tensor([1, 2, 3, 4, 9])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
# exponential 
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
# initialize a matrix with zeros
input = torch.zeros(2, 3, 4)
print(input.shape)
# swap the element 0 and 2
out = input.transpose(0, 2)
print(out.shape)

torch.Size([2, 3, 4])


torch.Size([4, 3, 2])

In [24]:
# stack tensor together
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
print(stacked_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# Torch NN(Trainer)

#### [Torch_NN Document](https://pytorch.org/docs/stable/nn.html)

In [4]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))

tensor([-4.4503,  1.6298, -3.6123], grad_fn=<SqueezeBackward4>)


#### Softmax function: probability distribution

In [3]:
import torch.nn.functional as f
tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output = f.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [6]:
# initialize embedding layer
vocab_size = 1000
embedded_dim = 100
embedding = nn.Embedding(vocab_size, embedded_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])

embedded_output = embedding(input_indices)
print(embedded_output.shape)

tensor([[-1.4996e+00, -6.6733e-01, -4.2005e-03, -6.2238e-01, -1.3870e+00,
          8.4411e-01,  4.6126e-01, -6.0413e-01,  2.3426e+00, -1.4980e+00,
         -1.1938e+00,  5.1646e-01,  4.7292e-01,  6.5138e-01,  1.1003e+00,
          3.9714e-01, -9.1082e-01, -7.4354e-01, -3.5110e-01,  3.3945e-01,
          8.5000e-01,  1.4677e-01,  9.9064e-01,  4.8180e-01,  1.4357e+00,
         -6.6440e-01,  8.2177e-01,  4.4125e-01, -1.2090e+00, -8.0341e-01,
          2.4029e+00, -1.0162e+00,  3.5460e-02,  2.6622e-01,  5.0750e-01,
         -4.5776e-01,  1.3804e+00, -3.7393e-01, -3.4509e-01,  5.2088e-01,
          4.2730e-01, -1.1087e+00,  1.1989e-02,  1.1203e+00,  1.7891e+00,
          7.9121e-01,  7.4537e-01,  5.9577e-01,  2.4072e-01, -1.4452e-01,
          9.3456e-01, -5.2609e-01, -7.6928e-01,  1.5356e+00,  1.5098e-01,
          7.1828e-01, -1.3994e-02,  4.4674e-01,  2.3815e+00, -6.5477e-01,
         -5.5225e-01,  4.8211e-01, -1.0292e+00,  2.8332e+00, -9.4680e-01,
         -6.2137e-01,  1.2247e+00, -1.